<a href="https://colab.research.google.com/github/CE334/CE334_230586_Kulshreshth_Chikara/blob/main/Lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd


In [4]:
##Create row & column vectors

row = np.array([1, 2, 3, 4, 5])
col = np.array([[1], [2], [3], [4], [5]])

print("Row Vector:", row)
print("Column Vector:\n", col)


Row Vector: [1 2 3 4 5]
Column Vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
##Create a 5×5 matrix
ma = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])
print("Matrix ma:\n", ma)


Matrix ma:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
##Get the 3rd row of matrix
third_row = ma[2, :]
print("3rd Row:", third_row)



3rd Row: [11 12 13 14 15]


In [10]:
##Get the 4th column of matrix
fourth_col = ma[:, 3]
print("4th Column:", fourth_col)



4th Column: [ 4  9 14 19 24]


In [13]:
row_sorted = np.sort(ma, axis=1)
col_sorted = np.sort(ma, axis=0)

print("Row-wise Sorted:\n", row_sorted)
print("Column-wise Sorted:\n", col_sorted)


Row-wise Sorted:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Column-wise Sorted:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [14]:
##For loop: if element > 2, multiply by 10 → matrix
b = ma.copy()
for i in range(b.shape[0]):
    for j in range(b.shape[1]):
        if b[i, j] > 2:
            b[i, j] *= 10

print("Matrix b:\n", b)


Matrix b:
 [[  1   2  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]


In [15]:
##Add matrices a and b
add_ab = ma + b
print("a + b:\n", add_ab)


a + b:
 [[  2   4  33  44  55]
 [ 66  77  88  99 110]
 [121 132 143 154 165]
 [176 187 198 209 220]
 [231 242 253 264 275]]


In [16]:
##Subtract matrix b from a
add_ab = ma + b
print("a + b:\n", add_ab)


a + b:
 [[  2   4  33  44  55]
 [ 66  77  88  99 110]
 [121 132 143 154 165]
 [176 187 198 209 220]
 [231 242 253 264 275]]


In [17]:
##Multiply a and b element-wise & matrix multiplication
element_mult = ma * b
matrix_mult = ma @ b   # or np.matmul(a, b)

print("Element-wise Multiplication:\n", element_mult)
print("Matrix Multiplication (a @ b):\n", matrix_mult)


Element-wise Multiplication:
 [[   1    4   90  160  250]
 [ 360  490  640  810 1000]
 [1210 1440 1690 1960 2250]
 [2560 2890 3240 3610 4000]
 [4410 4840 5290 5760 6250]]
Matrix Multiplication (a @ b):
 [[ 2141  2282  2450  2600  2750]
 [ 4846  5192  5700  6100  6500]
 [ 7551  8102  8950  9600 10250]
 [10256 11012 12200 13100 14000]
 [12961 13922 15450 16600 17750]]


In [18]:
##Divide each element by 18
a_div = ma / 18
b_div = b / 18

print("a / 18:\n", a_div)
print("b / 18:\n", b_div)


a / 18:
 [[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.33333333 0.38888889 0.44444444 0.5        0.55555556]
 [0.61111111 0.66666667 0.72222222 0.77777778 0.83333333]
 [0.88888889 0.94444444 1.         1.05555556 1.11111111]
 [1.16666667 1.22222222 1.27777778 1.33333333 1.38888889]]
b / 18:
 [[ 0.05555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 3.33333333  3.88888889  4.44444444  5.          5.55555556]
 [ 6.11111111  6.66666667  7.22222222  7.77777778  8.33333333]
 [ 8.88888889  9.44444444 10.         10.55555556 11.11111111]
 [11.66666667 12.22222222 12.77777778 13.33333333 13.88888889]]


In [20]:
##Inverse, Rank, Condition Number, SVD, Norm of a and b
from numpy.linalg import matrix_rank, cond, norm, svd, inv

def analyze_matrix(M, name):
    print(f"--- Matrix {name} ---")

    # Rank
    print("Rank:", matrix_rank(M))

    # Condition number
    print("Condition Number:", cond(M))

    # SVD
    U, S, Vt = svd(M)
    print("Singular Values:", S)

    # Norm
    print("Norm:", norm(M))

    # Inverse (if exists)
    if matrix_rank(M) == M.shape[0]:
        print("Inverse:\n", inv(M))
    else:
        print("Inverse: Does not exist (Matrix is singular)")
    print()

analyze_matrix(ma, "a")
analyze_matrix(b, "b")


--- Matrix a ---
Rank: 2
Condition Number: 3.5675570478720614e+17
Singular Values: [7.42540539e+01 3.36681954e+00 2.98266488e-15 1.53916447e-15
 2.08136977e-16]
Norm: 74.33034373659252
Inverse: Does not exist (Matrix is singular)

--- Matrix b ---
Rank: 3
Condition Number: 1.1160764850096235e+17
Singular Values: [7.41586515e+02 4.50039192e+01 5.39337161e+00 1.85062771e-14
 6.64458507e-15]
Norm: 742.9703897195366
Inverse: Does not exist (Matrix is singular)



In [21]:
##Norm, Inner Product, Outer Product of Column Vector
v = col.flatten()  # convert to 1D
print("Vector v:", v)

print("Norm:", norm(v))
print("Inner Product (v·v):", np.inner(v, v))
print("Outer Product:\n", np.outer(v, v))


Vector v: [1 2 3 4 5]
Norm: 7.416198487095663
Inner Product (v·v): 55
Outer Product:
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [22]:
##Write derivative(f, a, method, h) & test it
def derivative(f, a, method='central', h=0.01):
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Method must be forward, backward or central")

# Testing
print("Derivative of e^x at 0.5:", derivative(np.exp, 0.5))
print("Derivative of cos(x) at 0.5:", derivative(np.cos, 0.5))


Derivative of e^x at 0.5: 1.648748749525375
Derivative of cos(x) at 0.5: -0.4794175482185081


In [28]:
##Read AWS CSV using Pandas
df = pd.read_csv("AWS.csv")
print(df)


                    created_at  entry_id  Soil Temperature  Soil Moisture  \
0    2022-12-14T14:19:11+05:30     10830             21.06            817   
1    2022-12-14T14:20:13+05:30     10831             21.06            817   
2    2022-12-14T14:21:15+05:30     10832             21.06            817   
3    2022-12-14T14:22:18+05:30     10833             21.06            817   
4    2022-12-14T14:23:20+05:30     10834             21.06            817   
..                         ...       ...               ...            ...   
654  2022-12-26T14:37:18+05:30     11484             20.50            818   
655  2022-12-26T15:17:18+05:30     11485           4095.94            818   
656  2022-12-26T15:57:59+05:30     11486             20.50            818   
657  2022-12-26T16:58:03+05:30     11487             20.00            816   
658  2022-12-26T17:18:03+05:30     11488             19.75            816   

     Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage